name: dart_payway_partner
description: A self registration for aba payway
version: 1.0.0
repository: https://github.com/kechankrisna/aba_payway_gateway/tree/main/dart_payway_partner

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dio: ^5.3.2 # http client helper
  crypto: ^3.0.3 # hash helper
  intl: ^0.18.0 # date fomart
  logger: ^2.0.2
  encrypt: ^5.0.3
  pointycastle: ^3.7.3

dev_dependencies:
  dotenv: ^4.1.0
  lints: ^2.0.0
  test: ^1.21.0
