include: package:lints/recommended.yaml

analyzer:
  # example/ is a Flutter app with its own analysis
  exclude:
    - example/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types
    - prefer_final_locals
    - unawaited_futures
