name: dart_payway
description: Allow you to integrate your app in dart language with ABA PayWay
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.19.0


# Add regular dependencies here.
dependencies:
  dio: ^5.3.2 # http client helper
  crypto: ^3.0.3 # hash helper
  intl: ^0.18.0 # date fomart
  logger: ^2.0.2

dev_dependencies:
  dotenv: ^4.1.0
  lints: ^2.0.0
  test: ^1.21.0
