name: flutter_payway
description: This will implement dart payway for flutter project
version: 1.1.0+1
repository: https://github.com/kechankrisna/aba_payway_gateway/tree/main/flutter_payway

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_payway: # ^1.0.8+3
    path: ../dart_payway

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_dotenv: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/flutter_payway/assets/images/ic_generic.png
    - packages/flutter_payway/assets/images/ic_cards.png
    - packages/flutter_payway/assets/images/ic_payway.png
